### ISSUE TITLE
Change many if statements for forms to separate views

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#21]

**Comment by dandeduck** [comment]
While working on this I've stumbled upon an issue that I'm yet to find a good solution to. So if @tomtzook  could help me out... (also its past 4:20 am so I might just not see it) I have a view called save changes on the new branch, it redirects to the main view at the end, but it also supposed to remove some stuff from cookies, and I just didnt find online a solution for this... Did you encounter something like this before?

**Comment by tomtzook** [comment]
Check out first answer:
https://stackoverflow.com/questions/5595166/how-to-update-a-cookie-in-django.

**Comment by dandeduck** [comment]
> Check out first answer:
> https://stackoverflow.com/questions/5595166/how-to-update-a-cookie-in-django.
> 

Wouldn't this compile the html response and then change the cookie? that doesn't help... I'll try it out

**Comment by dandeduck** [comment]
hah, it works... Weird
