### ISSUE TITLE
Implement scheduled email sending depending on changes

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#26]
Should cache changes and send them with a timer from the last update (to a given order) dunno what's the best way to do this

**Comment by dandeduck** [comment]
@tomtzook what do you think about this? ^

**Comment by dandeduck** [comment]
The #50 issue relates to the basic sending of emails, this is not a problem. In this issue I want to discuss the best way notify the staff email about new orders, because I want to do that in a way, which will reduce the amount of emails per order. Basically, the user might save once after he is done, or he might save after every package is added, so we don't want to send an email every time. I thought that may be we will add the new data to the db where we would also mark the time (in the same entry) and we will have a routine running every couple of minutes on the server checking all the cached data for all orders. And if there is any that didn't have any changes for some time, then it will compile the data and send it out to the staff via email. (the entry might include the related order, so every order for a given user will be independent in this regard and we will be able to group updates based on that)

**Comment by dandeduck** [comment]
What do you think ? @tomtzook I don't know the best way to do this, thus I don't know what to research

**Comment by tomtzook** [comment]
Isn't it partially solved? with the cookies and stuff? So when the edit is done (with the save button) emails can be sent

**Comment by dandeduck** [comment]
I wish, but it still leaves the possibility of the user saving it more than once per thing or remembering a bit later to add something.

**Comment by dandeduck** [comment]
So we decided to send emails for all the changes, group them into threads and check out how it looks.
