### ISSUE TITLE
BUG with autocomplete

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#38]
When entering a custom address that was not found in google maps (rare) user has to press enter upon completion (when using such a field it's usually expected) otherwise the function will not be called and the entered parameters will be lost. Need to fix it somehow or handle it and clarify that the user has to do it

**Comment by tomtzook** [comment]
Hmmm this doesn't sound like a major issue, but could be a problem.
How about listening to when the text field becomes unfocused (i.e. the user doesn't use it anymore and use it to save?

**Comment by tomtzook** [comment]
I'll take a look at the API for the autocomplete field from google when I can (tonight) and see if I can find a good solution from there.

**Comment by dandeduck** [comment]
ok no problem thanks

**Comment by dandeduck** [comment]
So the autocomplete widget doesn't have any other events besides place changed. But on the bright side, this event doesn't fire only if the user enters a custom input and doesn't press enter, so it's not as bad as I thought. I am currently trying to figure out how to run something when unfocused....

**Comment by dandeduck** [comment]
ok I implemented it and added to the existing autocomplete PR
