### ISSUE TITLE
'...' icon hints edit there

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#39]
It felt to me that the edit button is somewhat expected to be behind this this, but there is no need for it in terms of space (probably will be clearer this way though)

**Comment by tomtzook** [comment]
What?

Can you elaborate and add more details to what this is about?

**Comment by dandeduck** [comment]
> What?
> 
> Can you elaborate and add more details to what this is about?

Sorry, I wasn't very clear. On the order edit page packages have a ' ... ' where you can see the notes. When I see it I think " editing" because this icon is usually used for this. Don't you think?

**Comment by dandeduck** [comment]
Usually it's used to "show more" which usually includes the edit link. Current edit btn position is a bit awkward when you look at it.

**Comment by tomtzook** [comment]
I see what you mean. I see no problem with it. So if you want, go ahead and put the `edit` button under it.

**Comment by dandeduck** [comment]
I just think it will be awkward still to have a button and some text in this thing. Makes more sense to me that the notes will also be a link that opens a modal or something. (if there are any notes)

**Comment by dandeduck** [comment]
Ummm from what I can tell this can't be done (with popovers) since you can only put text in there. For this well need a dropdown, and it won't be as good. It's fine, just gonna close it
