### ISSUE TITLE
Popover Buttons Glitch

### ISSUE THREAD

**Issue by tomtzook** [dandeduck/package-tracking-web#47]
So the problem I showed earlier is still a thing. It seems that the problem is showing on _firefox_ but not _chrome_. Suggestion for the future: test with multiple browsers.

![image](https://user-images.githubusercontent.com/17641355/112541432-0c9e4880-8dbc-11eb-9452-9a0d50e2c232.png)

**Comment by dandeduck** [comment]
Didn't see this issue until now, next time add it to a project. And I tested it on firefox and didn't see the issue...
