### ISSUE TITLE
Add sorting options to order edit?

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#48]

**Comment by tomtzook** [comment]
What do you mean by:
> sorting options in order edit

**Comment by dandeduck** [comment]
> What do you mean by:
> > sorting options in order edit

When looking at the packages, display them in a certain order (by status by city, by rate etc.)

**Comment by dandeduck** [comment]
> > What do you mean by:
> > > sorting options in order edit
> 
> When looking at the packages, display them in a certain order (by status by city, by rate etc.)

(in order edit) and may be also in order view, could also make the general packages layout a separate template

**Comment by tomtzook** [comment]
Doesn't seem that urgent

**Comment by dandeduck** [comment]
yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah
