### ISSUE TITLE
Potential excessive billing for places API

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#57]
The autocomplete functionality of the places API is expensive, but it can bill per session instead of per request. The built in widget checks which billing is cheaper and does it. The problem comes in because the places where the API is used are client side only while filling the autocomplete (so this will all be the same session) but when adding another package for example, it will resend the html, so it might cause the API to start a new session. From testing it seems like it might be the case.

**Comment by tomtzook** [comment]
We should test it. It seems that following [this](https://developers.google.com/maps/documentation/places/web-service/usage-and-billing#autocomplete) you will have to recreate the session key, or preserve it (in a cookie)?

Another option can be to avoid resending the html and use AJAX requests instead.

But again, needs to be tested

**Comment by dandeduck** [comment]
The sessions are resetting automatically after selecting an address. Turns out
