### ISSUE TITLE
Package create/edit pop-up

### ISSUE THREAD

**Issue by dandeduck** [dandeduck/package-tracking-web#7]
Needs to be implemented (related to the bootstrap branch and pr)

**Comment by dandeduck** [comment]
Also need to implement the saving of those changes into cookies

**Comment by dandeduck** [comment]
Also add validation

**Comment by tomtzook** [comment]
Use _html5_ validation:
- https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation
- https://www.sitepoint.com/html5-form-validation/

You will then need to activate the check manually (probably).

**Comment by dandeduck** [comment]
Validation is was separated into its own issue #23

**Comment by dandeduck** [comment]
The other remaining part in need of fixing has its own issue #16
